spring:
  profiles:
    include: swagger

  datasource:
    username: ${MYSQL_USER}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 50
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

oauth2:
  google:
    client-id: ${GOOGLE_ID}
    client-secret: ${GOOGLE_PASSWORD}
    redirect-uri: ${BASE_URL}/api/v1/users/google
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo

mail:
  id: ${MAIL_ID}
  password: ${MAIL_PASSWORD}

spotify:
  client:
    id: ${SPOTIFY_CLIENT_ID}
    secret : ${SPOTIFY_CLIENT_SECRET}

base:
  url: ${BASE_URL}

kakao:
  redirect: ${KAKAO_REDIRECT_URL}
  client-id: ${KAKAO_CLIENT_ID}
  secret: ${KAKAO_SECRET}